services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: ./scripts/run_web.sh
    volumes:
      - .:/app 
    ports:
      - "5000:5000"
    links:
      - rabbitmq
      - redis

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pitchparser
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure

  redis:
    image: redis:latest
    hostname: redis

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management  # Use management version to access web UI
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672"  # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./scripts/run_celery.sh
    environment:
      - CELERY_BROKER_URL=amqp://admin:mypass@rabbitmq//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app
    links:
      - rabbitmq
      - redis
    depends_on:
      - rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:
  rabbitmq_logs:
  redis_data:
